apiVersion: apps/v1api
kind: Deployment
metadata:
  name: offer-deployment
  labels:
    app: offer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
    spec:
      containers:
      - name: offer
        image: deekshithsn/offer
        ports:
        - containerPort: 1001
    
---

apiVersion: v1
kind: Service
metadata:
  name: offer-service
spec:
  selector:
    app: offer
  ports:
    - name: offer
      port: 1001
      targetPort: 1001
  type: ClusterIP